import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "components/header";
import { Footer } from "components/footer";
import { Table } from "components/table";
import { TableMobile } from "components/table-mobile";

const Home: NextPage = () => {
  return (
    <div className="font-fragile">
      <Head>
        <title>Fragile | Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="hidden md:block">
        <Table />
      </div>
      <div className="block md:hidden">
        <TableMobile />
      </div>
      <Footer />
    </div>
  );
};

export default Home;
